CREATE TABLE chat_messages
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sender_id    BIGINT                                  NOT NULL,
    recipient_id BIGINT,
    content      TEXT                                    NOT NULL,
    group_id     BIGINT,
    type         VARCHAR(255)                            NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_chat_messages PRIMARY KEY (id)
);

CREATE TABLE group_chat_members
(
    group_chat_id BIGINT NOT NULL,
    user_id       BIGINT NOT NULL,
    CONSTRAINT pk_group_chat_members PRIMARY KEY (group_chat_id, user_id)
);

CREATE TABLE group_chats
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    admin_id   BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_group_chats PRIMARY KEY (id)
);

ALTER TABLE chat_messages
    ADD CONSTRAINT FK_CHAT_MESSAGES_ON_GROUP FOREIGN KEY (group_id) REFERENCES group_chats (id);

ALTER TABLE chat_messages
    ADD CONSTRAINT FK_CHAT_MESSAGES_ON_RECIPIENT FOREIGN KEY (recipient_id) REFERENCES users (id);

ALTER TABLE chat_messages
    ADD CONSTRAINT FK_CHAT_MESSAGES_ON_SENDER FOREIGN KEY (sender_id) REFERENCES users (id);

ALTER TABLE group_chats
    ADD CONSTRAINT FK_GROUP_CHATS_ON_ADMIN FOREIGN KEY (admin_id) REFERENCES users (id);

ALTER TABLE group_chat_members
    ADD CONSTRAINT fk_grochamem_on_group_chat FOREIGN KEY (group_chat_id) REFERENCES group_chats (id);

ALTER TABLE group_chat_members
    ADD CONSTRAINT fk_grochamem_on_user FOREIGN KEY (user_id) REFERENCES users (id);