CREATE TABLE users
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username                 VARCHAR(100)                            NOT NULL,
    password                 VARCHAR(255)                            NOT NULL,
    email                    VARCHAR(255)                            NOT NULL,
    first_name               VARCHAR(100)                            NOT NULL,
    last_name                VARCHAR(100)                            NOT NULL,
    address                  VARCHAR(255),
    enabled                  BOOLEAN,
    last_password_reset_date TIMESTAMP WITHOUT TIME ZONE,
    last_login_date          TIMESTAMP WITHOUT TIME ZONE,
    activation_token         VARCHAR(255),
    role_id                  BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE chat_messages
    ADD CONSTRAINT FK_CHAT_MESSAGES_ON_SENDER FOREIGN KEY (sender_id) REFERENCES users (id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE group_chats
    ADD CONSTRAINT FK_GROUP_CHATS_ON_ADMIN FOREIGN KEY (admin_id) REFERENCES users (id);

ALTER TABLE likes
    ADD CONSTRAINT FK_LIKES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_RECIPIENT FOREIGN KEY (recipient_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_SENDER FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE notifications
    ADD CONSTRAINT FK_NOTIFICATIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE posts
    ADD CONSTRAINT FK_POSTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE group_chat_members
    ADD CONSTRAINT fk_grochamem_on_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_followers
    ADD CONSTRAINT fk_usefol_on_follower FOREIGN KEY (follower_id) REFERENCES users (id);

ALTER TABLE user_followers
    ADD CONSTRAINT fk_usefol_on_user FOREIGN KEY (user_id) REFERENCES users (id);