-- Kreiranje tabele comments sa automatski generisanim ID kolonom
CREATE TABLE comments (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          post_id BIGINT NOT NULL,
                          user_id BIGINT NOT NULL,
                          content TEXT NOT NULL,
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    -- Dodavanje ograničenja za strane ključeve
                          CONSTRAINT fk_post
                              FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
                          CONSTRAINT fk_user
                              FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
