CREATE TABLE image
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    path          VARCHAR(255)                            NOT NULL,
    is_compressed BOOLEAN                                 NOT NULL,
    uploaded_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_image PRIMARY KEY (id)
);

CREATE TABLE locations
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    country   VARCHAR(255),
    city      VARCHAR(255),
    address   VARCHAR(255),
    number    INTEGER                                 NOT NULL,
    latitude  DOUBLE PRECISION                        NOT NULL,
    longitude DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_locations PRIMARY KEY (id)
);

ALTER TABLE posts
    ADD image_id BIGINT;

ALTER TABLE posts
    ADD location_id BIGINT;

ALTER TABLE posts
    ADD CONSTRAINT uc_posts_image UNIQUE (image_id);

ALTER TABLE posts
    ADD CONSTRAINT FK_POSTS_ON_IMAGE FOREIGN KEY (image_id) REFERENCES image (id);

ALTER TABLE posts
    ADD CONSTRAINT FK_POSTS_ON_LOCATION FOREIGN KEY (location_id) REFERENCES locations (id);

ALTER TABLE posts
DROP
COLUMN image_url;

ALTER TABLE posts
DROP
COLUMN latitude;

ALTER TABLE posts
DROP
COLUMN longitude;

ALTER TABLE posts
DROP
COLUMN id;

ALTER TABLE likes
DROP
COLUMN id;

ALTER TABLE likes
DROP
COLUMN post_id;

ALTER TABLE likes
    ADD id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;

CREATE SEQUENCE IF NOT EXISTS notifications_id_seq;
ALTER TABLE notifications
    ALTER COLUMN id SET NOT NULL;
ALTER TABLE notifications
    ALTER COLUMN id SET DEFAULT nextval('notifications_id_seq');

ALTER SEQUENCE notifications_id_seq OWNED BY notifications.id;

ALTER TABLE posts
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;

ALTER TABLE posts
    ADD CONSTRAINT uc_posts_image UNIQUE (id);

CREATE SEQUENCE IF NOT EXISTS posts_id_seq;
ALTER TABLE posts
    ALTER COLUMN id SET NOT NULL;
ALTER TABLE posts
    ALTER COLUMN id SET DEFAULT nextval('posts_id_seq');

ALTER SEQUENCE posts_id_seq OWNED BY posts.id;

ALTER TABLE comments
DROP
COLUMN post_id;

ALTER TABLE comments
    ADD post_id BIGINT NOT NULL;

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_POST FOREIGN KEY (post_id) REFERENCES posts (id);

ALTER TABLE likes
    ADD post_id BIGINT NOT NULL;

ALTER TABLE likes
    ADD CONSTRAINT FK_LIKES_ON_POST FOREIGN KEY (post_id) REFERENCES posts (id);